AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Eir

  Sample SAM Template for Eir

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  OlaNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Ola  # Name for lambda function, if not set gets generated automatically
      Timeout: 3
      MemorySize: 128
      Handler: app.ola_name_lambda_handler
      CodeUri: functions/ola/
      Runtime: python3.8
      Events: # What is going to trigger the function (ex. Api, SQS)?
        HelloNameCaller: # Name of the event. (could be anything)
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ola
            Method: post

  ListBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ListBooks
      Timeout: 30
      MemorySize: 128
      Handler: app.books_list_lambda_handler
      CodeUri: functions/books/
      Runtime: python3.8
      Events:
        CreateBookCaller:
          Type: Api
          Properties:
            Path: /book
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable

  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateBook
      Timeout: 30
      MemorySize: 128
      Handler: app.books_create_lambda_handler
      CodeUri: functions/books/
      Runtime: python3.8
      Events:
        CreateBookCaller:
          Type: Api
          Properties:
            Path: /book
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable

  DeleteBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteBook
      Timeout: 30
      MemorySize: 128
      Handler: app.books_delete_lambda_handler
      CodeUri: functions/books/
      Runtime: python3.8
      Events:
        CreateBookCaller:
          Type: Api
          Properties:
            Path: /book/{id}
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: books
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OlaNameApi:
    Description: "API Gateway endpoint URL for Prod stage for Ola Name function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ola/"
  OlaNameFunction:
    Description: "Ola Name Lambda Function ARN"
    Value: !GetAtt OlaNameFunction.Arn
  OlaNameFunctionIamRole:
    Description: "Implicit IAM Role created for Ola Name function"
    Value: !GetAtt OlaNameFunctionRole.Arn

  BooksApi:
    Description: "API Gateway endpoint URL for Prod stage for Books related functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/book/"
