AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Eir

  Sample SAM Template for Eir

Parameters:
  Environment:
    Type: String
    Default: DEV
    Description: (Required) Environment type
    AllowedValues:
      - DEV
      - PROD
  Origin:
    Type: String
    Default: http://localhost:3000
    Description: (Required) Frontend web app "Origin" which is allowed for CORS.
    AllowedValues:
      - http://localhost:3000
      - https://main.d3pbzq317h5g22.amplifyapp.com

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        BOOKS_TABLE_NAME: !Sub ${Environment}_books
        ALLOW_METHODS: 'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'
        ALLOW_HEADERS: 'X-Amz-Date,X-Api-Key,X-Amz-Security-Token,X-Requested-With,X-Auth-Token,Referer,User-Agent,Origin,Content-Type,Authorization,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'
        ALLOW_ORIGIN: !Sub '${Origin}'

Resources:
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Environment}_API
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'X-Amz-Date,X-Api-Key,X-Amz-Security-Token,X-Requested-With,X-Auth-Token,Referer,User-Agent,Origin,Content-Type,Authorization,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        AllowOrigin: !Sub "'${Origin}'"
        MaxAge: "'600'"
        AllowCredentials: true
      Auth:
        Authorizers:
          EirCognitoAuthorizer:
            UserPoolArn: !GetAtt EirCognitoUserPool.Arn

  ListBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}_ListBooks
      Timeout: 30
      MemorySize: 128
      Handler: app.books_list_lambda_handler
      CodeUri: functions/books/
      Runtime: python3.8
      Events:
        ListBooksCaller:
          Type: Api
          Properties:
            RestApiId: !Ref MainApi
            Path: /book
            Method: get
            Auth:
              Authorizer: EirCognitoAuthorizer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable

  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}_CreateBook
      Timeout: 30
      MemorySize: 128
      Handler: app.books_create_lambda_handler
      CodeUri: functions/books/
      Runtime: python3.8
      Events:
        CreateBookCaller:
          Type: Api
          Properties:
            RestApiId: !Ref MainApi
            Path: /book
            Method: post
            Auth:
              Authorizer: EirCognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable

  DeleteBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}_DeleteBook
      Timeout: 30
      MemorySize: 128
      Handler: app.books_delete_lambda_handler
      CodeUri: functions/books/
      Runtime: python3.8
      Events:
        DeleteBooksCaller:
          Type: Api
          Properties:
            RestApiId: !Ref MainApi
            Path: /book/{id}
            Method: delete
            Auth:
              Authorizer: EirCognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable

  GetSingleBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}_GetBook
      Timeout: 30
      MemorySize: 128
      Handler: app.book_get_single_lambda_handler
      CodeUri: functions/books/
      Runtime: python3.8
      Events:
        GetSingleBookCaller:
          Type: Api
          Properties:
            RestApiId: !Ref MainApi
            Path: /book/{id}
            Method: get
            Auth:
              Authorizer: EirCognitoAuthorizer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}_books
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  EirCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${Environment}_EirCognitoUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: phone_number
          Required: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
        - phone_number
      SmsConfiguration:
        SnsCallerArn: !GetAtt EirCognitoSnsIamRole.Arn
        ExternalId: "b989b444-47ef-4609-b9ae-d127c035a44b"
#        SnsCallerArn: "arn:aws:iam::633292692150:role/service-role/testing_iam_role_for_cognito_sms_DEV_Eir2"
#        ExternalId: "9421ee89-95b0-4278-9fb5-766a4adc5bff"

  EirCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref EirCognitoUserPool
      ClientName: !Sub ${Environment}_EirCognitoUserPoolClient
      GenerateSecret: false

  EirCognitoSnsIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}_EirCognitoSnsIamRole
      Description: "IAM role to call SNS publish which in turn will send SMS message"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: "b989b444-47ef-4609-b9ae-d127c035a44b"
      Policies:
        - PolicyName: SnsPublishPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:publish
                Resource:
                  - "*"

Outputs:
  # TODO ishan 14-09-2021 Cleanup the output to only have the APIs
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Origin:
    Description: "Domain configured as allowed Origin"
    Value: !Sub '${Origin}'
  MainApi:
    Description: "API Gateway endpoint URL for Prod stage for Books related functions"
    Value: !Sub "https://${MainApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}_API"
  EirCognitoUserPool:
    Description: "Cognito User Pool ID"
    Value: !Sub "${EirCognitoUserPool}"
  EirCognitoUserPoolClient:
    Description: "Cognito User Pool Client ID"
    Value: !Sub "${EirCognitoUserPoolClient}"
